#! /bin/sh

bspc config border_width        2
bspc config window_gap         	5
bspc config top_padding		15

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config auto_cancel true

bspc config presel_border_color	white
bspc config focused_border_color gray55
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/deskcolors
~/.config/bspwm//panel | lemonbar -p &
