#!/bin/bash


clock()
{
date +%H:%M
}

desks()
{
echo -n $(bspc control --get-status | cut -d: -f2- | sed "s/[^ufo:,0-9]//gi;s/://g;s/\([UFO][0-9]\)/%{+u}\1%{-u}/;s/f/%{F-}/gi;s/o/%{F#$skybarcolor}/gi;")%{F-}
}

while true; do

source ~/.config/deskcolors
echo "%{U#$skybarcolor}%{c}$(desks)%{r}$(clock)"
sleep 1

done
